BASE_URL=
BROWSER=chrome
ENVIRONMENT=qa
HEADLESS=true
TIMEOUT_SECONDS=20
SCREENSHOT_ON_FAILURE=true

# Qentrix generated test inventory
PROJECT_NAME=360GlobalNet
WORK_ITEM_IDS=2182
TEST_CASE_IDS=2832
TEST_DATA_FILE=test-data/testdata.json
CREDENTIALS_FILE=test-data/credentials.csv
FRAMEWORK_ENGINE=Playwright
FRAMEWORK_TYPE=Standard
BUILD_TOOL=npm
