BASE_URL=https://www.saucedemo.com
BROWSER=chrome
ENVIRONMENT=qa
HEADLESS=true
TIMEOUT_SECONDS=20
SCREENSHOT_ON_FAILURE=true

# Qentrix generated test inventory
PROJECT_NAME=360GlobalNet
WORK_ITEM_IDS=2182,2058,3517
TEST_CASE_IDS=2832,3430,3443,3989
TEST_DATA_FILE=test-data/testdata.json
CREDENTIALS_FILE=test-data/credentials.csv
FRAMEWORK_ENGINE=WebdriverIO
FRAMEWORK_TYPE=Cucumber BDD
BUILD_TOOL=npm
