trigger:
  branches:
    include:
      - main
      - develop

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: "-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)"

stages:
  - stage: Install
    jobs:
      - job: MavenInstall
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: pom.xml
              goals: install
              options: -DskipTests

  - stage: Smoke
    dependsOn: Install
    jobs:
      - job: SmokeTests
        variables:
          CI: true
          HEADLESS: true
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: pom.xml
              goals: test
              options: -P smoke
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: target/cucumber-reports/results.xml
          - publish: allure-results
            condition: succeededOrFailed()
            artifact: allure-results

  - stage: Regression
    dependsOn: Smoke
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
    jobs:
      - job: RegressionTests
        variables:
          CI: true
          HEADLESS: true
        steps:
          - task: Maven@3
            inputs:
              mavenPomFile: pom.xml
              goals: test
              options: -P regression
          - task: PublishTestResults@2
            condition: succeededOrFailed()
            inputs:
              testResultsFormat: JUnit
              testResultsFiles: target/cucumber-reports/results.xml
          - publish: allure-results
            condition: succeededOrFailed()
            artifact: allure-results
